const API='https://ubtojlrfxoxbuvgajeos.supabase.co/functions/v1/tradeup-public';
const PAGE_SIZE=24;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const fmt=v=>v===null||v===undefined||v===''?'N/D':String(v);
const clean=n=>String(n||'').replace(/^StatTrak™\s+/,'').replace(/^Souvenir\s+/,'');
const ERROR_MESSAGES={QUERY_TOO_LONG:'A consulta é longa demais.',REQUEST_URI_TOO_LONG:'Este endereço ficou longo demais para ser processado.',RATE_LIMITED:'Muitas consultas em pouco tempo. Tente novamente em instantes.',ORIGIN_NOT_ALLOWED:'Este ambiente não está autorizado a consultar o catálogo.'};
let collection=null;let skins=[];let nextOffset=null;let hasMore=false;let skinLoading=false;
function rarityMark(rarity,size='standard'){const r=fmt(rarity);return '<span class="rarity-mark '+size+'" data-rarity="'+esc(r)+'"><span>'+esc(r)+'</span></span>';}
function collectionIdentity(name,size='standard'){const c=fmt(name);return '<span class="collection-identity '+size+'" title="'+esc(c)+'"><span class="collection-plate" aria-hidden="true">S</span><span class="collection-name">'+esc(c)+'</span></span>';}
function boolLabel(v){return v===true?'Sim':v===false?'Não':'N/D';}
function freshness(v){if(v===null||v===undefined||v==='')return 'N/D';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString('pt-BR');}
function safeFrom(){const from=new URLSearchParams(location.search).get('from')||'';return from&&from.startsWith('/')&&!from.startsWith('//')?from:'';}
function currentHubUrl(name){return location.pathname+'?collection='+encodeURIComponent(name)+(safeFrom()?'&from='+encodeURIComponent(safeFrom()):'');}
function stateBox(title,detail,error=false,retry=false){const b=$('entityState');b.hidden=false;b.className='state-box'+(error?' error':'');b.innerHTML='<strong>'+esc(title)+'</strong><span>'+esc(detail)+'</span>'+(retry?'<button id="retryBtn" class="text-button" type="button">Tentar novamente</button>':'');if(retry&&$('retryBtn'))$('retryBtn').onclick=loadCollection;}
function skinsState(title,detail='',error=false){const b=$('skinsState');b.hidden=false;b.className='state-box'+(error?' error':'');b.innerHTML='<strong>'+esc(title)+'</strong>'+(detail?'<span>'+esc(detail)+'</span>':'');}
function applyOrigin(){const from=safeFrom();if(!from)return;$('originContext').hidden=false;$('breadcrumbBack').href=from;$('contextBackBtn').href=from;if(/\/database\/skin\//.test(from)){$('originLabel').textContent='Vindo de uma skin';$('originHelper').textContent='Volte à skin sem perder o contexto anterior.';$('contextBackBtn').textContent='Voltar à skin';$('breadcrumbBack').textContent='Skin Hub';}else if(/\/database\/collections\//.test(from)){$('originLabel').textContent='Vindo de Coleções';$('originHelper').textContent='Sua busca e seus filtros permanecem no endereço anterior.';$('contextBackBtn').textContent='Voltar às coleções';$('breadcrumbBack').textContent='Coleções';}else{$('originLabel').textContent='Contexto anterior';$('originHelper').textContent='Retorne ao ponto de origem preservado.';$('contextBackBtn').textContent='Voltar';}}
function skinHref(x){return '../../skin/?key='+encodeURIComponent(x.market_key||x.skin_name||'')+'&from='+encodeURIComponent(currentHubUrl(collection.collection_name||collection.collection_key||''));}
function art(x){return x.image_url?'<img src="'+esc(x.image_url)+'" alt="'+esc(clean(x.skin_name))+'" loading="lazy">':'<span class="skin-meta">imagem N/D</span>';}
function renderCollection(x){collection=x;$('entityHub').hidden=false;$('entityState').hidden=true;const name=x.collection_name||x.collection_key||'N/D';$('crumbName').textContent=name;$('collectionName').textContent=name;$('collectionIdentityHero').innerHTML=collectionIdentity(name,'standard');$('skinCount').textContent=fmt(x.skin_count);$('variantCount').textContent=fmt(x.variant_count);$('hasStattrak').textContent=boolLabel(x.has_stattrak);$('hasConsumer').textContent=boolLabel(x.has_consumer_grade);const rarities=Array.isArray(x.rarities_present)&&x.rarities_present.length?x.rarities_present.map(r=>rarityMark(r)).join(''):'N/D';$('raritiesPresent').innerHTML=rarities;$('catalogUpdatedAt').textContent=freshness(x.catalog_updated_at);document.title='SCALE — '+name+' · Collection Hub';}
function renderSkins(items){skins=items;$('skinsGrid').innerHTML=items.map(x=>'<article class="skin-card explorer-card"><a class="skin-card-main" href="'+skinHref(x)+'">'+art(x)+'<div class="card-identity"><h3>'+esc(clean(x.skin_name))+'</h3></div><div class="item-classification">'+rarityMark(x.rarity,'compact')+collectionIdentity(x.collection,'compact')+'</div><div class="card-badges">'+(x.is_stattrak?'<span class="mini-tag">StatTrak</span>':'')+'<span class="mini-tag muted">float '+esc(fmt(x.float_min))+'–'+esc(fmt(x.float_max))+'</span></div><span class="card-action">Abrir skin →</span></a></article>').join('');}
function updatePagination(){const b=$('loadMoreBtn');b.hidden=!hasMore;b.disabled=skinLoading;b.textContent=skinLoading?'Carregando…':'Carregar mais skins';}
async function loadSkins({append=false,offset=0}={}){if(!collection)return;skinLoading=true;updatePagination();const name=collection.collection_name||collection.collection_key||'';if(!append)skinsState('Carregando skins…');try{const p=new URLSearchParams();p.set('collection',name);p.set('limit',String(PAGE_SIZE));p.set('offset',String(offset));p.set('ui','1');const r=await fetch(API+'?'+p.toString());const d=await r.json().catch(()=>({status:'ERROR',error:'INVALID_RESPONSE'}));if(!r.ok||d.status==='ERROR'){const code=d.error||('HTTP_'+r.status);if(!append)renderSkins([]);hasMore=false;nextOffset=null;$('skinsTitle').textContent='Não foi possível carregar as skins';skinsState(ERROR_MESSAGES[code]||'Não foi possível consultar as skins desta coleção.',code,true);return;}const page=Array.isArray(d.items)?d.items:[];const merged=append?[...skins,...page]:page;renderSkins(merged);const pg=d.pagination||{};hasMore=pg.has_more===true;nextOffset=Number.isFinite(Number(pg.next_offset))?Number(pg.next_offset):null;if(merged.length){$('skinsTitle').textContent=merged.length+' skins carregadas';skinsState(hasMore?'Há mais skins nesta coleção.':'Lista carregada para esta coleção.');}else{$('skinsTitle').textContent='Nenhuma skin encontrada';skinsState('Nenhuma skin foi encontrada para esta coleção.');}}catch(_){if(!append)renderSkins([]);hasMore=false;nextOffset=null;$('skinsTitle').textContent='Não foi possível carregar as skins';skinsState('Não foi possível consultar as skins desta coleção.','NETWORK_ERROR',true);}finally{skinLoading=false;updatePagination();}}
async function loadCollection(){const key=new URLSearchParams(location.search).get('collection')?.trim()||'';if(key.length<2){stateBox('Coleção não encontrada.','Volte ao Explorer de coleções e escolha outra coleção.',true,false);return;}stateBox('Carregando coleção…','Carregando os dados desta coleção.');try{const p=new URLSearchParams();p.set('entity','collection');p.set('collection',key);p.set('limit','50');p.set('offset','0');p.set('sort','default');const r=await fetch(API+'?'+p.toString());const d=await r.json().catch(()=>({status:'ERROR',error:'INVALID_RESPONSE'}));if(!r.ok||d.status==='ERROR'){const code=d.error||('HTTP_'+r.status);stateBox('Não foi possível carregar esta coleção.',ERROR_MESSAGES[code]||code,true,true);return;}const items=Array.isArray(d.items)?d.items:[];const exact=items.find(x=>x.collection_name===key||x.collection_key===key);if(!exact){stateBox('Coleção não encontrada.','Não encontramos uma coleção exata para este identificador.',true,false);return;}renderCollection(exact);await loadSkins();}catch(_){stateBox('Não foi possível carregar esta coleção.','NETWORK_ERROR',true,true);}}
$('loadMoreBtn').onclick=()=>{if(hasMore&&nextOffset!==null&&!skinLoading)loadSkins({append:true,offset:nextOffset});};
applyOrigin();loadCollection();